package com.nightbeam.donutshards.model;
public enum TransactionType { REWARD, SHOP_PURCHASE, ADMIN_GIVE, ADMIN_TAKE, ADMIN_SET, PLAYER_TRANSFER, CONVERSION, KILL_REWARD, REFUND, ROLLBACK, MIGRATION, API }
