package com.nightbeam.donutshards.command;
import com.nightbeam.donutshards.model.*;import com.nightbeam.donutshards.scheduler.SchedulerService;import com.nightbeam.donutshards.service.MessageService;import com.nightbeam.donutshards.shop.ShopService;import com.nightbeam.donutshards.transaction.TransactionService;import com.nightbeam.donutshards.zone.ZoneService;import org.bukkit.*;import org.bukkit.command.*;import org.bukkit.entity.Player;import java.util.*;
public final class CommandRouter implements CommandExecutor,TabCompleter {private final TransactionService tx;private final SchedulerService scheduler;private final MessageService messages;private final ZoneService zones;private final ShopService shop;private final int tax;public CommandRouter(TransactionService tx,SchedulerService scheduler,MessageService messages,ZoneService zones,ShopService shop,int tax){this.tx=tx;this.scheduler=scheduler;this.messages=messages;this.zones=zones;this.shop=shop;this.tax=tax;}
 public boolean onCommand(CommandSender sender,Command command,String label,String[] args){return switch(command.getName()){case "shards"->shards(sender,args);case "shardshop"->shop(sender);case "afk"->afk(sender,args);case "shardmanager"->admin(sender,args);default->false;};}
 private boolean shards(CommandSender s,String[] a){if(!(s instanceof Player p)){s.sendMessage("Players only.");return true;}if(a.length==0||a[0].equalsIgnoreCase("balance")){var target=p;if(a.length>1&&p.hasPermission("shards.balance.others")){var found=Bukkit.getPlayerExact(a[1]);if(found!=null)target=found;}var finalTarget=target;tx.balance(target.getUniqueId()).whenComplete((v,e)->reply(p,()->messages.send(p,e==null?"<gray><player>'s balance: <light_purple><balance></light_purple>":"<red>Database unavailable.</red>",e==null?Map.of("player",finalTarget.getName(),"balance",Long.toString(v)):Map.of())));return true;}if(a[0].equalsIgnoreCase("pay")&&a.length==3){var target=Bukkit.getPlayerExact(a[1]);var amount=parse(a[2]);if(target==null||amount<1){messages.send(p,"<red>Usage: /shards pay <online-player> <amount></red>",Map.of());return true;}var ctx=new MutationContext(TransactionType.PLAYER_TRANSFER,"player-transfer",p.getUniqueId(),"pay:"+UUID.randomUUID(),Map.of());tx.transfer(p.getUniqueId(),target.getUniqueId(),amount,tax,ctx).whenComplete((r,e)->reply(p,()->messages.send(p,e==null&&r.success()?"<green>Sent <amount> shards to <player> (tax <tax>).</green>":"<red>Transfer failed: <reason></red>",e==null?Map.of("amount",Long.toString(amount),"player",target.getName(),"tax",Long.toString(r.tax()),"reason",r.reason()):Map.of("reason","storage_error"))));return true;}messages.send(p,"<gray>/shards balance [player] | /shards pay <player> <amount></gray>",Map.of());return true;}
 private boolean shop(CommandSender s){if(s instanceof Player p)shop.open(p);else s.sendMessage("Players only.");return true;}
 private boolean afk(CommandSender s,String[] a){if(!(s instanceof Player p)){s.sendMessage("Players only.");return true;}if(a.length>0&&a[0].equalsIgnoreCase("leave")){zones.leave(p.getUniqueId());messages.send(p,"<gray>You left the AFK zone.</gray>",Map.of());}else messages.send(p,"<gray>No AFK zones are configured yet.</gray>",Map.of());return true;}
 private boolean admin(CommandSender s,String[] a){if(!s.hasPermission("shards.admin")){messages.send(s,"<red>No permission.</red>",Map.of());return true;}if(a.length>=3&&(a[0].equalsIgnoreCase("give")||a[0].equalsIgnoreCase("take")||a[0].equalsIgnoreCase("set"))){var target=Bukkit.getOfflinePlayer(a[1]);var amount=parse(a[2]);if(amount<0){messages.send(s,"<red>Invalid amount.</red>",Map.of());return true;}var type=a[0].equalsIgnoreCase("give")?TransactionType.ADMIN_GIVE:a[0].equalsIgnoreCase("take")?TransactionType.ADMIN_TAKE:TransactionType.ADMIN_SET;var ctx=new MutationContext(type,"admin:"+a[0].toLowerCase(Locale.ROOT),s instanceof Player p?p.getUniqueId():null,"admin:"+UUID.randomUUID(),Map.of());var result=a[0].equalsIgnoreCase("give")?tx.add(target.getUniqueId(),amount,ctx):a[0].equalsIgnoreCase("take")?tx.remove(target.getUniqueId(),amount,ctx):tx.set(target.getUniqueId(),amount,ctx);result.whenComplete((r,e)->scheduler.global(()->s.sendMessage(e==null&&r.success()?"Balance updated.":"Update failed: "+(e==null?r.reason():"storage error"))));return true;}s.sendMessage("/shardmanager give|take|set <player> <amount>");return true;}
 private void reply(Player p,Runnable task){scheduler.entity(p,task,()->{});}private long parse(String text){try{return Long.parseLong(text);}catch(NumberFormatException e){return -1;}}
 public List<String> onTabComplete(CommandSender s,Command c,String l,String[] a){if(a.length==1)return c.getName().equals("shardmanager")?List.of("give","take","set","reset","reload","history","rollback","zone","migrate","debug","version","gui"):c.getName().equals("afk")?List.of("list","join","leave","random","info"):List.of("balance","pay","top","history","convert");return List.of();}}
