package com.nightbeam.donutshards.service;
import com.nightbeam.donutshards.integration.vault.VaultHook;import com.nightbeam.donutshards.model.*;import com.nightbeam.donutshards.transaction.TransactionService;import org.bukkit.entity.Player;import java.util.Map;import java.util.UUID;
public final class ConversionService {private final TransactionService tx;private final VaultHook vault;private volatile boolean enabled;private volatile int shardsPerDollar;private volatile int feeBasisPoints;private volatile long minimumShards;private volatile double minimumDollars;
 public ConversionService(TransactionService tx,VaultHook vault){this.tx=tx;this.vault=vault;}
 public void reload(org.bukkit.configuration.file.YamlConfiguration config){enabled=config.getBoolean("conversion.enabled",true);shardsPerDollar=Math.max(1,config.getInt("conversion.shards-per-dollar",100));feeBasisPoints=Math.max(0,Math.min(10000,config.getInt("conversion.fee-basis-points",0)));minimumShards=Math.max(1,config.getLong("conversion.minimum-shards",1));minimumDollars=Math.max(0.01,config.getDouble("conversion.minimum-dollars",0.01));}
 public boolean enabled(){return enabled&&vault.available();}
 public java.util.concurrent.CompletionStage<ConversionResult> convert(Player player,String amountText,String direction){if(!enabled())return java.util.concurrent.CompletableFuture.completedFuture(ConversionResult.failure("conversion_disabled"));if(!player.hasPermission("shards.convert"))return java.util.concurrent.CompletableFuture.completedFuture(ConversionResult.failure("no_permission"));var dir=direction==null?"":direction.toLowerCase(java.util.Locale.ROOT);if(dir.equals("shards")||dir.equals("money"))return doConvert(player,amountText,dir);return java.util.concurrent.CompletableFuture.completedFuture(ConversionResult.failure("invalid_direction"));}
 private java.util.concurrent.CompletionStage<ConversionResult> doConvert(Player player,String amountText,String direction){if(direction.equals("money"))return shardsToMoney(player,parseLong(amountText));return moneyToShards(player,parseDouble(amountText));}
 private java.util.concurrent.CompletionStage<ConversionResult> shardsToMoney(Player player,long shards){if(shards<1)return java.util.concurrent.CompletableFuture.completedFuture(ConversionResult.failure("invalid_amount"));if(shards<minimumShards)return java.util.concurrent.CompletableFuture.completedFuture(ConversionResult.failure("below_minimum_shards"));var dollars=shards/(double)shardsPerDollar;dollars=applyFee(dollars);if(dollars<minimumDollars)return java.util.concurrent.CompletableFuture.completedFuture(ConversionResult.failure("below_minimum_dollars"));var ctx=new MutationContext(TransactionType.CONVERSION,"vault:shards-to-money",player.getUniqueId(),"convert:"+UUID.randomUUID(),Map.of("direction","shards-to-money","shards",Long.toString(shards)));var finalDollars=dollars;return tx.remove(player.getUniqueId(),shards,ctx).thenCompose(result->{if(!result.success())return java.util.concurrent.CompletableFuture.completedFuture(ConversionResult.failure(result.reason()));if(!vault.economy().depositPlayer(player,finalDollars).transactionSuccess()){var refund=new MutationContext(TransactionType.CONVERSION,"vault:refund",player.getUniqueId(),"convert-refund:"+UUID.randomUUID(),Map.of());return tx.add(player.getUniqueId(),shards,refund).thenApply(r->ConversionResult.failure("vault_deposit_failed"));}return java.util.concurrent.CompletableFuture.completedFuture(ConversionResult.success(shards,finalDollars,"shards-to-money"));});}
 private java.util.concurrent.CompletionStage<ConversionResult> moneyToShards(Player player,double dollars){if(dollars<=0)return java.util.concurrent.CompletableFuture.completedFuture(ConversionResult.failure("invalid_amount"));if(dollars<minimumDollars)return java.util.concurrent.CompletableFuture.completedFuture(ConversionResult.failure("below_minimum_dollars"));var rawShards=(long)Math.floor(dollars*shardsPerDollar);var shards=applyFeeShards(rawShards);if(shards<minimumShards)return java.util.concurrent.CompletableFuture.completedFuture(ConversionResult.failure("below_minimum_shards"));if(!vault.economy().has(player,dollars)||!vault.economy().withdrawPlayer(player,dollars).transactionSuccess())return java.util.concurrent.CompletableFuture.completedFuture(ConversionResult.failure("insufficient_funds"));var ctx=new MutationContext(TransactionType.CONVERSION,"vault:money-to-shards",player.getUniqueId(),"convert:"+UUID.randomUUID(),Map.of("direction","money-to-shards","dollars",Double.toString(dollars)));var finalShards=shards;var finalDollars=dollars;return tx.add(player.getUniqueId(),finalShards,ctx).thenApply(result->{if(result.success())return ConversionResult.success(finalShards,finalDollars,"money-to-shards");vault.economy().depositPlayer(player,finalDollars);return ConversionResult.failure(result.reason());});}
 private double applyFee(double amount){return amount*(10_000-feeBasisPoints)/10_000.0;}
 private long applyFeeShards(long shards){if(feeBasisPoints<=0)return shards;return Math.max(0,(long)Math.floor(shards*(10_000L-feeBasisPoints)/10_000.0));}
 private long parseLong(String text){try{return Long.parseLong(text);}catch(NumberFormatException e){return -1;}}
 private double parseDouble(String text){try{return Double.parseDouble(text);}catch(NumberFormatException e){return -1;}}
 public record ConversionResult(boolean success,String reason,long shards,double dollars,String direction){public static ConversionResult success(long shards,double dollars,String direction){return new ConversionResult(true,"ok",shards,dollars,direction);}public static ConversionResult failure(String reason){return new ConversionResult(false,reason,0,0,"");}}
}
